global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hotel-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hotel-api:8080']
        labels:
          application: 'hotel-reservation-api'
          environment: 'docker'

